### ISSUE TITLE
error using dammit GFF3Parser in binder

### ISSUE THREAD

**Issue by ljcohen** [camillescott/dammit#105]
I would love to use dammit's `GFF3Parser` function in a binder for this repo:

https://github.com/ljcohen/Fundulus_heteroclitus_genome_stats

[![Binder](https://mybinder.org/badge.svg)](https://mybinder.org/v2/gh/ljcohen/Fundulus_heteroclitus_genome_stats/master)

My understanding is the [requirements.txt](https://github.com/ljcohen/Fundulus_heteroclitus_genome_stats/blob/master/requirements.txt) uses `pip install`. Everything seemed to launch successfully when the binder was created, no errors installing dammit. However, when I executed this command from the notebook:

`from dammit.fileio.gff3 import GFF3Parser` 

the following error occurred:

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-9-7b94f9e9ce01> in <module>()
      1 import pandas as pd
----> 2 from dammit.fileio.gff3 import GFF3Parser

/srv/venv/lib/python3.6/site-packages/dammit/__init__.py in <module>()
      2 
      3 import logging
----> 4 import log
      5 logger = log.DammitLogger()
      6 

ModuleNotFoundError: No module named 'log'
```

Is there anything I can include in my [requirements.txt](https://github.com/ljcohen/Fundulus_heteroclitus_genome_stats/blob/master/requirements.txt) to fix this?

**Comment by camillescott** [comment]
Ah, this is probably because I've yet to push 1.0 to PyPI :) I'll do that.

**Comment by ljcohen** [comment]
Awesome, thank you!

**Comment by camillescott** [comment]
Try `dammit==1.0rc0` in your binder requirements, that should bring the new version in.

**Comment by camillescott** [comment]
Sorry, scratch that -- you want `dammit==1.0rc2` in your reqs, or `pip install dammit==1.0rc2` manually.

**Comment by ljcohen** [comment]
`from dammit.fileio.gff3 import GFF3Parser` works from the launched binder now, thank you!
