### ISSUE TITLE
Error in maf-gff3 step

### ISSUE THREAD

**Issue by ctb** [camillescott/dammit#12]
```
          [ ] maf-gff3:cdna_nointrons_utrs.fa.x.orthodb.maf.gff3

     # Some tasks failed!                                             [dammit.annotate:ERROR]
     # TaskError - taskid:maf-                                        [dammit.annotate:ERROR]
     # gff3:cdna_nointrons_utrs.fa.x.orthodb.maf.gff3
     # PythonAction Error Traceback (most recent call last):   File   [dammit.annotate:ERROR]
     # "/usr/local/lib/python2.7/dist-
     # packages/doit-0.29.0-py2.7.egg/doit/action.py", line 383, in
     # execute     returned_value = self.py_callable(*self.args,
     # **kwargs)   File "/usr/local/lib/python2.7/dist-
     # packages/dammit-0.0.5-py2.7-linux-
     # x86_64.egg/dammit/tasks.py", line 374, in cmd     for group
     # in parsers.maf_to_df_iter(input_filename):   File
     # "/usr/local/lib/python2.7/dist-packages/dammit-0.0.5-py2.7
     # -linux-x86_64.egg/dammit/parsers.py", line 377, in
     # maf_to_df_iter     yield build_df(data, LAMBDA, K)   File
     # "/usr/local/lib/python2.7/dist-packages/dammit-0.0.5-py2.7
     # -linux-x86_64.egg/dammit/parsers.py", line 326, in build_df
     # df['bitscore'] = (LAMBDA * df['score'] - np.log(K)) /
     # np.log(2)   File "/usr/local/lib/python2.7/dist-
     # packages/pandas-0.17.0-py2.7-linux-
     # x86_64.egg/pandas/core/ops.py", line 618, in wrapper
     # return left._constructor(wrap_results(na_op(lvalues,
     # rvalues)),   File "/usr/local/lib/python2.7/dist-
     # packages/pandas-0.17.0-py2.7-linux-
     # x86_64.egg/pandas/core/ops.py", line 563, in na_op
     # result[mask] = op(x[mask], y) TypeError: unsupported operand
     # type(s) for *: 'float' and 'NoneType'
```

**Comment by ctb** [comment]
Reproducible on just the first 3 sequences (but much faster ;)

**Comment by ctb** [comment]
'LAMBDA' is None, line 326 of parsers.py

**Comment by camillescott** [comment]
I can see how this might happen, but I can't for the life of me reproduce it. Can you give me the MAF file it's choking on?

**Comment by ctb** [comment]
On Mon, Nov 02, 2015 at 09:52:12PM -0800, Camille Scott wrote:
> I can see how this might happen, but I can't for the life of me reproduce it. Can you give me the MAF file it's choking on?

It's 100% reproducible on Ubuntu 14.04; may take me a few days to get
to reproducing it, though.

**Comment by ctb** [comment]
Full dammit output here: http://athyra.idyll.org/~t/cdna_nointrons_utrs.fa.dammit.tar.gz (3 MB)

**Comment by ctb** [comment]
Turns out to be lastal version problem, I think.

```
dpkg -l | grep last-align
ii  last-align                       393-1                               amd64
```

The last-align version is quite old and its output doesn't have lambda in the maf file. Installing last-658 seemed to fix the MAF parsing problem; I'll fix #9.

**Comment by ctb** [comment]
Reopening; this should probably be something that's checked in the dependencies step.

**Comment by camillescott** [comment]
Ahh, good find. 15.04 has a newer version, which is why I missed it -- I
suppose I'll add version checks for all the dependencies.

On Thu, Nov 5, 2015 at 2:50 PM, C. Titus Brown <notifications@github.com>
wrote:

> Reopening; this should probably be something that's checked in the
> dependencies step.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/camillescott/dammit/issues/12#issuecomment-154220910>.
>



-- 
Camille Scott

Department of Computer Science
Lab for Data Intensive Biology
University of California, Davis

camille.scott.w@gmail.com

**Comment by ctb** [comment]
On Thu, Nov 05, 2015 at 03:50:01PM -0800, Camille Scott wrote:
> Ahh, good find. 15.04 has a newer version, which is why I missed it -- I
> suppose I'll add version checks for all the dependencies.

I'm currently also fixing a pandas versioning issue :).

**Comment by camillescott** [comment]
Version check added in v0.2.6
