### ISSUE TITLE
Sphinx issue (setuptools too?)

### ISSUE THREAD

**Issue by butterflyology** [camillescott/dammit#14]
### It's probably me, not you, but...

running *make install* goes well until I get this error:

  Found existing installation: Sphinx 1.2.3
Cannot remove entries from nonexistent file /Users/Chris/anaconda/lib/python2.7/site-packages/easy-install.pth
make: *** [deps] Error 1

I've tried uninstalling and reinstalling everything with *pip*, but I see that setuptools is not creating the easy-install.pth object (which it should, right?) I'm not a regular *python* user so if this is on me I'm happy to remove the issue. 

Cheers

CH

**Comment by butterflyology** [comment]
After a fresh git pull I have the same problem as two days ago. Here is the all of the output from terminal:

Chris-MacBook-Pro:dammit Chris$ make install
pip install --requirement requirements.txt
Requirement already satisfied (use --upgrade to upgrade): setuptools>=0.6.35 in /Users/Chris/anaconda/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): pandas>=0.16.2 in /Users/Chris/anaconda/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): khmer>=2.0 in /Users/Chris/anaconda/lib/python2.7/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): doit>=0.29.0 in /Users/Chris/anaconda/lib/python2.7/site-packages (from -r requirements.txt (line 4))
Collecting sphinxcontrib-napoleon>=0.3.11 (from -r requirements.txt (line 5))
  Downloading sphinxcontrib_napoleon-0.3.11-py2.py3-none-any.whl (166kB)
    100% |████████████████████████████████| 167kB 1.3MB/s 
Collecting Sphinx>=1.3.1 (from -r requirements.txt (line 6))
  Downloading Sphinx-1.3.1-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 207kB/s 
Requirement already satisfied (use --upgrade to upgrade): sphinx-rtd-theme>=0.1.9 in /Users/Chris/anaconda/lib/python2.7/site-packages (from -r requirements.txt (line 7))
Collecting nose==1.3.4 (from -r requirements.txt (line 8))
  Downloading nose-1.3.4-py2-none-any.whl (154kB)
    100% |████████████████████████████████| 155kB 1.7MB/s 
Collecting nose-capturestderr==1.0 (from -r requirements.txt (line 9))
  Downloading nose-capturestderr-1.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in /Users/Chris/anaconda/lib/python2.7/site-packages (from pandas>=0.16.2->-r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): pytz>=2011k in /Users/Chris/anaconda/lib/python2.7/site-packages (from pandas>=0.16.2->-r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.7.0 in /Users/Chris/anaconda/lib/python2.7/site-packages (from pandas>=0.16.2->-r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): bz2file in /Users/Chris/anaconda/lib/python2.7/site-packages (from khmer>=2.0->-r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): screed>=0.9 in /Users/Chris/anaconda/lib/python2.7/site-packages (from khmer>=2.0->-r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): cloudpickle in /Users/Chris/anaconda/lib/python2.7/site-packages (from doit>=0.29.0->-r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): six in /Users/Chris/anaconda/lib/python2.7/site-packages (from doit>=0.29.0->-r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): configparser in /Users/Chris/anaconda/lib/python2.7/site-packages (from doit>=0.29.0->-r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): macfsevents in /Users/Chris/anaconda/lib/python2.7/site-packages (from doit>=0.29.0->-r requirements.txt (line 4))
Collecting pockets>=0.2.1 (from sphinxcontrib-napoleon>=0.3.11->-r requirements.txt (line 5))
  Downloading pockets-0.2.4-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): snowballstemmer>=1.1 in /Users/Chris/anaconda/lib/python2.7/site-packages (from Sphinx>=1.3.1->-r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): Pygments>=2.0 in /Users/Chris/anaconda/lib/python2.7/site-packages (from Sphinx>=1.3.1->-r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): docutils>=0.11 in /Users/Chris/anaconda/lib/python2.7/site-packages (from Sphinx>=1.3.1->-r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): babel>=1.3 in /Users/Chris/anaconda/lib/python2.7/site-packages (from Sphinx>=1.3.1->-r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.3 in /Users/Chris/anaconda/lib/python2.7/site-packages (from Sphinx>=1.3.1->-r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): alabaster<0.8,>=0.7 in /Users/Chris/anaconda/lib/python2.7/site-packages (from Sphinx>=1.3.1->-r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in /Users/Chris/anaconda/lib/python2.7/site-packages (from Jinja2>=2.3->Sphinx>=1.3.1->-r requirements.txt (line 6))
Building wheels for collected packages: nose-capturestderr
  Running setup.py bdist_wheel for nose-capturestderr
  Stored in directory: /Users/Chris/Library/Caches/pip/wheels/7b/cb/6b/9bbb3232ea2d7d3e17890a686ac5063a410db060eb108eae1b
Successfully built nose-capturestderr
Installing collected packages: Sphinx, pockets, sphinxcontrib-napoleon, nose, nose-capturestderr
  Found existing installation: Sphinx 1.2.3
Cannot remove entries from nonexistent file /Users/Chris/anaconda/lib/python2.7/site-packages/easy-install.pth
make: *** [deps] Error 1

**Comment by camillescott** [comment]
This looks like an issue with your configuration. What happens when you just run `pip install Sphinx sphinxcontrib-napoleon`?

**Comment by camillescott** [comment]
Re: our conversation yesterday, this was addressed in a recent update to the Anaconda installation instructions in the docs. Closing.

**Comment by stxlvt** [comment]
See also https://github.com/pypa/pip/issues/2751
