### ISSUE TITLE
hmmscan very sloooooow

### ISSUE THREAD

**Issue by macmanes** [camillescott/dammit#19]
Camille:

an enhancement here:

`hmmscan` is very slow, even with `--cpu N`. It turns out that the speedup associated with threads is minimal. Instead, what works much better, is to split the fasta into N jobs, and run those each with `--cpu 1`, then merge the output in the end. Does this make sense?

**Comment by Blahah** [comment]
This is true for almost all files that operate on a fasta using a database. BLAST for example is much faster when run using a split input than when run with multiple threads. Could be applied across the board perhaps @camillescott ?

**Comment by camillescott** [comment]
I'm hoping to incorporate this functionality eventually. In the meantime, `hmmscan` is much much faster now that an evalue cutoff is being passed to it directly.

**Comment by camillescott** [comment]
You'll be pleased to hear I've finally done this in v0.2.9. Closing :)
