### ISSUE TITLE
gff/busco/last

### ISSUE THREAD

**Issue by macmanes** [camillescott/dammit#20]
Camille:

Just finished dammit. It took a long time, but cool now that it is done: the `dammit.gff3` starts with `##gff-version 3.2.1` followed by about 300k empty lines at the top of the file. Not sure what happened there.

1. It might be nice to make a fasta output as well with the 'essential annotation'

```
>Transcript_123 gene=SLC2A1 hmmer_domains=X,Y,Z CDS=A-B,C-D,D-E
``` 

2. How are the BUSCO results incorporated into the gff? I don't see any obvious connection.

3. Maybe you could use the BUSCO report to flag potential duplicate sequences?

4. Maybe filter the LAST/HMMER results by e-value. Seems like reporting all hits might be too much.

**Comment by camillescott** [comment]
Thanks @macmanes, these are good comments! I've now fixed the blank lines in master, and that release will be pushed shortly.

1. This will be done soon™
2. This is a pretty good idea -- for now I need to at least get the BUSCO hits into the merged GFF3, and put the results in a more obvious place.
3. In the current master branch now only the best hits are reported; this will get into the same release as the blank lines issue.

**Comment by camillescott** [comment]
Relevant unfixed portions covered in #65, closing.
