### ISSUE TITLE
Challenges with downloaded databases

### ISSUE THREAD

**Issue by ctb** [camillescott/dammit#21]
I'm getting this with the pre-installed/configured databases that I tarred up, posted to S3, and then downloaded into a new location.  My guess is that something about their location or configuration is recorded in the dammit db in that directory, and since the location has changed, dammit isn't detecting that they're already pressed. Any thoughts?

```
--- Installing databases

          [x] download_and_gunzip:Pfam-A.hmm

          [ ] hmmpress:Pfam-A.hmm


Error: Looks like /dammit-db/Pfam-A.hmm is already pressed (.h3i file present, anyway):
Delete old hmmpress indices first
          [x] download_and_gunzip:Rfam.cm

          [ ] cmpress:Rfam.cm


Error: Looks like /dammit-db/Rfam.cm is already pressed (.i1i file present, anyway): delete old cmpress indices first, or use -F
          [x] download_and_gunzip:aa_seq_euk.fasta

          [ ] lastdb:aa_seq_euk.fasta.db
```

**Comment by camillescott** [comment]
Yeah, this is a bug that's fixed in master but not in the release yet. Has to do with how the relevant tasks were handling file dependencies. Will be fixed once I push a new release this afternoon :)

**Comment by ctb** [comment]
OK, please let me know when you make the new release!

**Comment by camillescott** [comment]
@ctb sent a mail to the lab list
