### ISSUE TITLE
Update dependencies req/tests for 0.0.8

### ISSUE THREAD

**Issue by ctb** [camillescott/dammit#25]
So far it needs matplotlib and sklearn in addition to other stuff.

**Comment by ctb** [comment]
also, needs ficus and python-tk (for ficus). crb-blast is still tested as a dependency, which would appear to be incorrect now?

**Comment by ctb** [comment]
If you're interested in the list of what is needed to get dammit to execute & say that all dependencies are satisfied, please see:

https://github.com/ctb/2015-docker-building/blob/master/dammit/Dockerfile

**Comment by ctb** [comment]
(That's for v0.0.8)

**Comment by camillescott** [comment]
Fixed in 0.0.9
