### ISSUE TITLE
DataFrame.sort_values requires pandas 0.17 or above.

### ISSUE THREAD

**Issue by ctb** [camillescott/dammit#28]
It's not in pandas 0.16.0, which is what is packaged with ubuntu 15.10.

**Comment by ctb** [comment]
It'd be great if either dammit worked with pandas 0.13 (also see issue #15), and/or if the version requirements specified the right version of pandas (issue #25).

**Comment by camillescott** [comment]
For now, this is resolved by an updated requirements file. I will leave the original issue open for future discussion.
