### ISSUE TITLE
Error installing databases

### ISSUE THREAD

**Issue by bacms2** [camillescott/dammit#33]
I am getting an error when using dammit databases --install after installing it using pip. I firstly assumed this was due to a different version of ConfigParser but updating to the beta version has not solved it. Can you point me on the right direction to solve it. Error is:
--- Installing databases

Traceback (most recent call last):
  File "/usr/local/bin/dammit", line 9, in <module>
    app.DammitApp().run()
  File "/usr/local/lib/python2.7/dist-packages/dammit/app.py", line 31, in run
    self.args.func()
  File "/usr/local/lib/python2.7/dist-packages/dammit/app.py", line 166, in handle_databases
    databases.DatabaseHandler(self.args).handle()
  File "/usr/local/lib/python2.7/dist-packages/dammit/databases.py", line 66, in handle
    common.run_tasks(self.tasks, doit_args, config=self.doit_config)
  File "/usr/local/lib/python2.7/dist-packages/dammit/common.py", line 43, in run_tasks
    DoitMain(Loader()).run(args)
  File "/usr/local/lib/python2.7/dist-packages/doit/doit_cmd.py", line 59, in **init**
    ini_config = self.load_config_ini(config_filenames)
  File "/usr/local/lib/python2.7/dist-packages/doit/doit_cmd.py", line 72, in load_config_ini
    cfg_parser = ConfigParser(allow_no_value=True, delimiters=('=',))

Versions of software are:
pip 7.1.2 from /usr/local/lib/python2.7/dist-packages (python 2.7)
dammit (0.1.1)
configparser (3.5.0b2)

Running on debian 8.2

**Comment by camillescott** [comment]
Did you happen to upgrade from an older version of dammit? If so, try removing `databases.doit.db` from your databases directory and running `dammit databases --install` again (it'll be in ~/.dammit/databases if you're running with the default location).

Otherwise, I don't think it's a configparser issue -- you have the same version as my testing systems. Can you try checking your pydoit version with `doit --version`?

**Comment by bacms2** [comment]
I tried you suggestion but made no difference. Doit version is the lastest
version (0.29.0) but I add to import it directly from python as running it
directly gives the same problem as before
~$ doit --version
Traceback (most recent call last):
  File "/usr/local/bin/doit", line 9, in <module>
    load_entry_point('doit==0.29.0', 'console_scripts', 'doit')()
  File "/usr/local/lib/python2.7/dist-packages/doit/__main__.py", line 8,
in main
    sys.exit(DoitMain().run(sys.argv[1:]))
  File "/usr/local/lib/python2.7/dist-packages/doit/doit_cmd.py", line 59,
in __init__
    ini_config = self.load_config_ini(config_filenames)
  File "/usr/local/lib/python2.7/dist-packages/doit/doit_cmd.py", line 72,
in load_config_ini
    cfg_parser = ConfigParser(allow_no_value=True, delimiters=('=',))
TypeError: __init__() got an unexpected keyword argument 'delimiters'

**Comment by camillescott** [comment]
This is quite curious. Some further research shows that the `delimiters` keyword was introduced in the Python 3.5 version of configparser, which was backported to Python 2 via configparser 3.5.0b2, ie this package: https://pypi.python.org/pypi/configparser. Your reported version up there is correct, but I'm guessing your Python environment is finding an older one. Can you manually inspect the configparser version in /usr/local/lib/python2.7/dist-packages? I suspect that it will be the older one.

**Comment by camillescott** [comment]
Okay, @bacms2, it's been a long while, but I *finally* figured out this error. For some reason, old versions of the configparser backport don't get removed from site-packages. The solution is:

1) Remove all versions of configparser with `pip install configparser`, as many times as necessary.
2) `ls` your site-packages folder and `grep` for configparser. You'll probably find an errant folder.
3) Remove it!
4) Do a `pip install configparser==configparser==3.5.0b2`
5) Magic! It should now work

I can only assume this is a bug with the configparser package, so I'll be filing an issue with them.

Cheers,
Camille

**Comment by bacms2** [comment]
Dear Camile,

Thank you very much for getting back to me on this. I had kind of given up
on it but actually just had a new request to install it again from another
member of the department and ended up finding the problematics folder
on site-packages and delete it seem to have solved the problem so you are
right on track.

Thank you very much for the help.

Best,
Bruno

**Comment by harryjubb** [comment]
@camillescott Thank you! Working on my own pipeline with doit and couldn't find anything on this error; you have saved me a lot of time!

All the best,

Harry

**Comment by abaten** [comment]
Thanks Camile. I tried to fix it six months ago. Banged my head in the wall and gave it up. 
Came back to it today, saw this thread and now it's working fine.
Cheers!

**Comment by camillescott** [comment]
Glad to be of help all :) Gonna close this issue for now, but it shall remain here, archived, as an oasis on the return trek from the deserts of stackoverflow barren of solutions for this bug.
