### ISSUE TITLE
--full not working to download uniref90

### ISSUE THREAD

**Issue by macmanes** [camillescott/dammit#36]
using dammit 0.2.0

```
$ dammit databases --install --full --database-dir /mnt/harmonia/
========================================
dammit! a tool for easy de novo transcriptome annotation
Camille Scott 2015
========================================

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
submodule: databases
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

--- Checking PATH for dependencies

          [x] TransDecoder

          [x] LAST

          [x] HMMER

          [x] Infernal

          [x] crb-blast

          [x] BLAST+

          [x] BUSCO


--- Dependency results

          All dependencies satisfied!


--- Checking for database prep (dir: /mnt/harmonia)

          [ ] download_and_gunzip:Pfam-A.hmm

          [ ] hmmpress:Pfam-A.hmm

          [ ] download_and_gunzip:Rfam.cm

          [ ] cmpress:Rfam.cm

          [ ] download_and_gunzip:aa_seq_euk.fasta

          [ ] lastdb:aa_seq_euk.fasta.db

          [ ] download_and_gunzip:ODB8_EukOGs_genes_ALL_levels.txt

          [ ] download_and_untar:harmonia-metazoa

--- Database results

          Database prep incomplete
```

**Comment by camillescott** [comment]
Yeah, this is a purposeful regression in 0.2.0, as --full wasn't being run
in the annotation stage anyhow. I'll be putting together a list of known
issues today and adding this, though it will be reactivated in an upcoming
version.

On Thu, Dec 10, 2015 at 4:02 AM, Matt MacManes <notifications@github.com>
wrote:

> using dammit 0.2.0
>
> $ dammit databases --install --full --database-dir /mnt/harmonia/
> ========================================
> dammit! a tool for easy de novo transcriptome annotation
> Camille Scott 2015
> ========================================
>
>
> submodule: databases
>
>
> --- Checking PATH for dependencies
>
>           [x] TransDecoder
>
>           [x] LAST
>
>           [x] HMMER
>
>           [x] Infernal
>
>           [x] crb-blast
>
>           [x] BLAST+
>
>           [x] BUSCO
>
>
> --- Dependency results
>
>           All dependencies satisfied!
>
>
> --- Checking for database prep (dir: /mnt/harmonia)
>
>           [ ] download_and_gunzip:Pfam-A.hmm
>
>           [ ] hmmpress:Pfam-A.hmm
>
>           [ ] download_and_gunzip:Rfam.cm
>
>           [ ] cmpress:Rfam.cm
>
>           [ ] download_and_gunzip:aa_seq_euk.fasta
>
>           [ ] lastdb:aa_seq_euk.fasta.db
>
>           [ ] download_and_gunzip:ODB8_EukOGs_genes_ALL_levels.txt
>
>           [ ] download_and_untar:harmonia-metazoa
>
> --- Database results
>
>           Database prep incomplete
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/camillescott/dammit/issues/36>.
>



-- 
Camille Scott

Department of Computer Science
Lab for Data Intensive Biology
University of California, Davis

camille.scott.w@gmail.com
