### ISSUE TITLE
install databases in parallel?

### ISSUE THREAD

**Issue by macmanes** [camillescott/dammit#43]
Camille:

Why not do some of the database install stuff in parallel, with a user flag `--threads INT`? Lots of us have multicore machines, could make it a lot faster..

Matt

**Comment by camillescott** [comment]
Currently the `--threads` argument is passed to each database command where applicable, but I could change it to execute the tasks themselves in parallel via doit. I'll run some tests to see if this causes too much disk access or memory usage (a couple of the db prep tasks really gobble up the ram).

**Comment by camillescott** [comment]
This is in the 1.0 branch now; closing.
