### ISSUE TITLE
Error in BLAST remap

### ISSUE THREAD

**Issue by camillescott** [camillescott/dammit#51]
[originally from @abshah]

Hi Camille, 
I just tried running the example datasets and ended up with a slightly different error! 

`--- Running annotate!

          Transcriptome file: cdna_nointrons_utrs.fa

          Output directory: /home/abhijeet/dammit_test/cdna_nointrons_utrs.fa.dammit

          [ ] cdna_nointrons_utrs.fa

          [ ] transcriptome_stats:cdna_nointrons_utrs.fa

          [ ] busco:cdna_nointrons_utrs.fa-eukaryota

          [ ] TransDecoder.LongOrfs:cdna_nointrons_utrs.fa

          [ ] hmmscan:longest_orfs.pep.x.Pfam-A.hmm

          [ ] remap_hmmer:longest_orfs.pep.pfam.tbl

          [ ] TransDecoder.Predict:cdna_nointrons_utrs.fa

          [ ] cmscan:cdna_nointrons_utrs.fa.x.Rfam.cm

          [ ] lastal:cdna_nointrons_utrs.fa.x.orthodb.maf

          [ ] sanitize_fasta:pep.fa

          [ ] crb-blast:cdna_nointrons_utrs.fa.x.pep.fa

          [ ] maf_best_hits:cdna_nointrons_utrs.fa.x.orthodb.maf-
          cdna_nointrons_utrs.fa.x.orthodb.maf.best.csv

          [ ] maf-gff3:cdna_nointrons_utrs.fa.x.orthodb.maf.gff3

          [ ] hmmscan-gff3:cdna_nointrons_utrs.fa.pfam.csv.gff3

          [ ] cmscan-gff3:cdna_nointrons_utrs.fa.rfam.tbl.gff3

          [ ] crbb-gff3:cdna_nointrons_utrs.fa.x.pep.fa.crbb.tsv.gff3

Some tasks failed![dammit.annotate:ERROR]
TaskError - taskid:crbb-gff3:cdna_nointrons_utrs.fa.x.pep.fa.crbb.tsv.gff3[dammit.annotate:ERROR]
PythonAction Error
Traceback (most recent call last):
  File "/home/abhijeet/anaconda2/lib/python2.7/site-packages/doit/action.py", line 383, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/home/abhijeet/anaconda2/lib/python2.7/site-packages/dammit/tasks.py", line 539, in cmd
    remap=True):
  File "/home/abhijeet/anaconda2/lib/python2.7/site-packages/dammit/parsers.py", line 284, in crb_to_df_iter
    remap_blast(group)
  File "/home/abhijeet/anaconda2/lib/python2.7/site-packages/dammit/blast.py", line 68, in remap_blast_coords_df
    df['sstrand'] = coords[coords:,4]
IndexError: invalid slice
[dammit.annotate:ERROR]
Some tasks failed![dammit.annotate:ERROR]
UnmetDependency - taskid:gff3-merge:cdna_nointrons_utrs.fa.dammit.gff3[dammit.annotate:ERROR]
crbb-gff3:cdna_nointrons_utrs.fa.x.pep.fa.crbb.tsv.gff3
[dammit.annotate:ERROR]
Some tasks failed![dammit.annotate:ERROR]
UnmetDependency - taskid:fasta-annotate:cdna_nointrons_utrs.fa.dammit.fasta[dammit.annotate:ERROR]
gff3-merge:cdna_nointrons_utrs.fa.dammit.gff3
[dammit.annotate:ERROR]`

**Comment by mpj5142** [comment]
I'm running this on the test data now (I had the same issue as @abshah), but I think it could be a typo/bug in blast.py:

Line 68 reads
``df['sstrand'] = coords[coords:,4]``
But maybe it should be 
``df['sstrand'] = coords[:,4]``
as the rest of the remapping functions follow that pattern.

I'll report back after re-running the code with the correction...

**Comment by mpj5142** [comment]
That fix worked! I'm pretty new to GitHub so I don't want to mess anything up with a pull request...

**Comment by camillescott** [comment]
Indeed, it is definitely just a typo (and I'm kind of vexed how it got past the acceptance tests) -- I intend to push a new release tomorrow, but I've been very swamped with the end of our quarter :) I really ought to put up some contributor instructions for people to help with fixes like this!

**Comment by mpj5142** [comment]
Glad I could help!

**Comment by abshah** [comment]
Runs fine now! 
Thanks @camillescott and @mpj5142

**Comment by camillescott** [comment]
Officially fixed in 0.2.8, thanks all!
