### ISSUE TITLE
LAST dep issue

### ISSUE THREAD

**Issue by camillescott** [camillescott/dammit#58]
from @Victaphanta:

---

DAMMIT - Same problem here. Installed all dependencies, followed by dammit itself - all appropriately in PATH, and then ran >dammit dependencies and all is in order except LAST:
lastal: invalid option -- '-'
lastal: bad option
......
[ ] LAST... [1]
[x] crb-blast

--- Dependency results

      LAST missing
Also tried LAST-737 which compiled with -std=c++11, which apparently is needed for multithreading. Still no cookie.

Any help would be appreciated.
Look forward to testing you pipeline. Thanks for making it available

---

**Comment by Victaphanta** [comment]
Hi Camille,  still no work around with having the dependency LAST recognised, due to this "invalid option --'-'.  Reinstalled everything again as per your instruction and still the same issue.  Any suggestions?  Thanks in advance.

**Comment by camillescott** [comment]
There's a fix now in the master branch :) If you do:

    git clone https://github.com/camillescott/dammit.git

and install:

    cd dammit
    make install

You'll have the version which uses gnu-parallel and drops the invalid option. I'll be pushing a stable release to PyPI sometime today.
