### ISSUE TITLE
hmmpress:Pfam-A.hmm database won't install

### ISSUE THREAD

**Issue by Jorisvansteenbrugge** [camillescott/dammit#63]
When installing the databases with the command: `dammit databases --install`, all databases install except for hmmpress:Pfam-A.hmm. I get the following error:

> Some tasks failed![DatabaseHandler:ERROR]
> TaskFailed - taskid:hmmpress:Pfam-A.hmm[DatabaseHandler:ERROR]
> Command failed: '/usr/bin/hmmpress /home/jsteenbrugge/.dammit/databases/Pfam-A.hmm' returned 1
> [DatabaseHandler:ERROR]

I tried to remove the databases.doit.db file but this did not fix it. Furthermore I tried different versions of dammit (v0.3 & v0.3.1.dev0) but this did not fix the problem unfortunately. 
Also I tried the binary /usr/bin/hmmpress which seems to work fine.

**Comment by camillescott** [comment]
Can you attach the last few hundred lines of the log file? You can grab it with:

    tail -n 200 ~/.dammit/log/dammit-all.log

Cheers,
Camille

**Comment by Jorisvansteenbrugge** [comment]
Hi Camille,

Here is the log file:
[dammitLog.txt](https://github.com/camillescott/dammit/files/313517/dammitLog.txt)

**Comment by camillescott** [comment]
Thinking about this a bit more, I wonder if it could have to do with the hmmer version. When you say you tried the binary at /usr/bin/hmmpress, you mean you tried it on the Pfam-A.hmm in the .databases dir?

**Comment by Jorisvansteenbrugge** [comment]
The only thing I tried at the time was if the hmmpress binary was installed correctly, I did not try to run it on the Pfam-A.hmm file. Unfortunately that was on a server at my internship on which I don't have access currently so I am not able to try that.

**Comment by camillescott** [comment]
There's another possibility that I recently had pop up with another user -- the original Pfam-A download might have been interrupted and resulted in a truncated file. On occasion this seems to happen in such a way that `curl` doesn't return an error code, and so pydoit marks the task as completed successfully. Yet Another Milestone for 1.0 is to do MD5 checks on all the databases to control for this, but in the meantime, the best solution is to just delete that database and let dammit redownload it.
