### ISSUE TITLE
Unable to install db; [DatabaseHandler:ERROR]

### ISSUE THREAD

**Issue by aspanjer** [camillescott/dammit#68]
When trying to do a full database install I get the following message:

Some tasks failed![DatabaseHandler:ERROR]
TaskFailed - taskid:lastdb:aa_seq_euk.fasta.db[DatabaseHandler:ERROR]
Command failed: '/usr/bin/lastdb -w3 -p /home/andrew/.dammit/databases/aa_seq_euk.fasta.db /home/andrew/.dammit/databases/aa_seq_euk.fasta' returned 1
[DatabaseHandler:ERROR]

any suggestions...

**Comment by camillescott** [comment]
Might be a LAST issue. Can you give me some of your log file with `tail -n 200 ~/.dammit/log/dammit-all.log`?

**Comment by aspanjer** [comment]
06-22 13:15:39 DatabaseHandler:write:85 [ERROR] 
Some tasks failed!
-----
06-22 13:15:39 DatabaseHandler:write:85 [ERROR] 
TaskFailed - taskid:lastdb:aa_seq_euk.fasta.db
-----
06-22 13:15:39 DatabaseHandler:write:85 [ERROR] 
Command failed: '/usr/bin/lastdb -w3 -p /home/andrew/.dammit/databases/aa_seq_euk.fasta.db /home/andrew/.dammit/databases/aa_seq_euk.fasta' returned 1

-----
06-22 13:15:39 DatabaseHandler:write:85 [DEBUG] 

-----
06-22 13:15:39 DatabaseHandler:write:85 [DEBUG] 
lastdb: out of memory

These were the last few lines with errors...looks like a memory problem. Do you have an idea what the minimum memory requirement is?

Thanks for the help!

**Comment by camillescott** [comment]
Sorry for the really long wait! `lastdb` will consume 16+ GB for OrthoDB, and even more for uniref. Would it be useful for me to host some prebuilt databases for the larger ones?
