### ISSUE TITLE
Issue with logger

### ISSUE THREAD

**Issue by aihardin** [camillescott/dammit#69]
Hi! I've installed everything successfully with pip but when trying to run dammit I'm getting this error:

$ dammit
Traceback (most recent call last):
  File "/usr/local/bin/dammit", line 4, in <module>
    import dammit
  File "/usr/local/lib/python3.4/dist-packages/dammit/__init__.py", line 5, in <module>
    logger = log.DammitLogger()
AttributeError: 'module' object has no attribute 'DammitLogger'

**Comment by camillescott** [comment]
This results from running dammit 0.3 on python3, which is currently unsupported. However, I'm about to release 1.0, which is python3 compatible (along with fixing a whole bunch of things)
