### ISSUE TITLE
Observation of output gff3 file

### ISSUE THREAD

**Issue by abshah** [camillescott/dammit#70]
Hi dammit users, 

I have noticed that the GFF3 file output by dammit has is slightly inconsistent.  The start and stop positions for some results from Infernal (especially the ones on the - strand) are switched. This may cause issues if you try to load the GFF3 file and process it with IRanges and rtracklayer packages (from BioConductor, see below for code and error). However, it is perhaps trivial to fix it in your favorite scripting language, but it maybe ideal we can fix this in later dammit releases ? 

Best,
Abhijeet

`>library(rtracklayer)
>my_dammit_anno<-import.gff3("my_anno.dammit.gff3")
Error in .Call2("solve_user_SEW0", start, end, width, PACKAGE = "IRanges") : 
  solving row 2621: negative widths are not allowed
In addition: Warning message:
In .local(con, format, text, ...) :
  gff-version directive indicates version is 3.2.1, not 3`

**Comment by camillescott** [comment]
Thanks for filing this! This has been addresses in the beta of the 1.0 release (which is on the branch refactor/1.0) and should be in master relatively soon.
